export const heartContentArray = [
  "I love you more than Lionel loves peeing on rugs",
  "ur a sweetpea :)",
  "If being beautiful was a crime you'd be in jail",
  "I want to spank you (in a sexy way)",
  "sweet potato pie",
  "You're the cutest ever",
  "Let's go dancing together",
  "You're the Jumbling Towers champion!",
  "I love playing board games with you",
  "Driving you around is one of my favorite things",
  "Let's play Mario Party (fuck Daisy)",
  "Thank you for being you",
  "I love you",
  "I love being able to clean your dishes",
  "You're the best travel partner",
  "You're my favorite person",
  "You are so so so so so so beautiful",
  "You make me feel so special and so lucky",
  "I'm so thankful for you",
  "I love holding your hand",
  "I want to kiss your face",
];