export const heartContentArray = [
  "I love you more than Lionel loves peeing on rugs",
  "ur a sweetpea :)",
  "If being beautiful was a crime you'd be in jail",
  "I want to spank you (in a sexy way)",
  "sweet potato pie",
  "You're the cutest ever",
  "I'll never get tired of dancing with you",
  "Jumble my towers",
  "I love playing board games with you",
  "Driving you around is one of my favorite things",
  "Let's play Mario Party (fuck Daisy)",
  "Thank you for being you",
  "I love you",
  "I love being able to clean your dishes",
  "You're the best travel partner",
  "You're my favorite person",
  "You are so so so so so so beautiful",
  "You make me feel so special and so lucky",
  "I'm so thankful for you",
  "I love holding your hand",
  "I want to kiss your face",
  "I love you, every day a little more",
  "Get ready, I'm about to flirt with you ;)",
  "I like it when you call me Lionel's dad :)",
  "You smell... really good ;)",
  "I love making your bed for you",
  "You've got that good Elle smell",
  "Who's hot and sexy? YOU'RE HOT AND SEXY!",
  "I'd sacrifice myself for you in the Hunger Games",
  "Admit it, you have a crush on me ;)",
  "Ur the best baker this side of the Mississippi",
  "U R smart, beautiful, talented, and valid",
  "You inspire me to always be better",
  "I love making you laugh",
  "Bite me ;)",
  "CHOMP!",
  "I love when we share new music with each other",
  "I want to squeeze your butt",
  "*whispers* lil bitsssss",
  "You tryna... cuddle?",
  "You're a superstar!",
  "My little storm cloud",
  "My little venus fly trap",
  "Baby Cakes",
  "U R Kenough",
];